services:
  sql:
    image: mysql/mysql-server:5.7
    container_name: ies_mysql_ex3
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=secret1
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=secret2
    ports: 
      - "33060:3306"
  app:
    depends_on:
      - sql
    build: ./app
    ports:
       - "8080:8080"
    volumes:
    - .m2:/root/.m2
